# Generated by Django 5.0.6 on 2024-06-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_profile_user'),
        ('chat', '0003_userprofile'),
    ]

    operations = [
    ]
